[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "local can_skip = next(find_joker('Shortcut'))"
position = "after"
payload = '''
local can_loop = next(find_joker('Elizabeth Tower'))
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = '''
    for j = 1, 14 do
      if IDS[j == 1 and 14 or j] then
        straight_length = straight_length + 1
        skipped_rank = false
        for k, v in ipairs(IDS[j == 1 and 14 or j]) do
          t[#t+1] = v
        end
      elseif can_skip and not skipped_rank and j ~= 14 then
          skipped_rank = true
      else
        straight_length = 0
        skipped_rank = false
        if not straight then t = {} end
        if straight then break end
      end
      if straight_length >= (5 - (four_fingers and 1 or 0)) then straight = true end 
    end
'''
position = "at"
payload = '''
    for j = 1, 22 do
      if IDS[j == 1 and 14 or j == 15 and 2 or j == 16 and 3 or j == 17 and 4 or j == 18 and 5
            or j == 19 and 6 or j == 20 and 7 or j == 21 and 8 or j == 22 and 9 or j] then
        if not can_loop and j > 14 then goto continue end
        straight_length = straight_length + 1
        skipped_rank = false
        for k, v in ipairs(IDS[j == 1 and 14 or j == 15 and 2 or j == 16 and 3 or j == 17 and 4 or j == 18 and 5
                              or j == 19 and 6 or j == 20 and 7 or j == 21 and 8 or j == 22 and 9 or j]) do
          t[#t+1] = v
        end
      elseif can_skip and not skipped_rank and j <= 14 then
          skipped_rank = true
      else
        straight_length = 0
        skipped_rank = false
        if not straight then t = {} end
        if straight then break end
      end
      if straight_length >= (5 - (four_fingers and 1 or 0)) then straight = true end 
      ::continue::
    end
'''
match_indent = false
times = 1